[general]
library_name = "libaeron"
output_file_path = "../src/LibAeron.jl"
module_name = "LibAeron"
# jll_pkg_name = "Aeron_jll"
export_symbol_prefixes = ["aeron_"]
prologue_file_path = "./prologue.jl"
epilogue_file_path = "./epilogue.jl"



# use_julia_native_enum_type = true

# We want to be able to create unintialized context structs and let the library fill them in
auto_mutability = false
# auto_mutability_with_new = true
# auto_mutability_includelist  = [
#     "aeron_context_stct",
# ]

extract_c_comment_style = "doxygen"
show_c_function_prototype = true

# # use deterministic symbol instead of `gensym`-generated `var"##XXX"`
# use_deterministic_symbol = true
# smart_de_anonymize = true


[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true


[codegen.macro]
# it‘s highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"

